fix

diff --git a/.github/workflows/actions.yml b/.github/workflows/actions.yml
--- a/.github/workflows/actions.yml
+++ b/.github/workflows/actions.yml
@@ -24,21 +24,27 @@ jobs:
         run: |
           main_branch="main"
           exit_code=0
-
+          
           IFS=$'\n' read -rd '' -a commit_ids <<<"${COMMIT_IDS}"
           
           echo "Checking commits: ${commit_ids[@]}"
-
+          
           for commit_id in "${commit_ids[@]}"; do
-              if ! git branch --contains "$commit_id" | grep -q "$main_branch"; then
-                  exit_code=1
-                  echo "Commit $commit_id is not in the $main_branch branch."
-                  break
-              fi
+           if ! git branch --contains "$commit_id" | grep -q "$main_branch"; then
+               exit_code=1
+               echo "Commit $commit_id is not in the $main_branch branch."
+               break
+           fi
           done
-
+          
           if [ $exit_code -eq 0 ]; then
-              echo "All commit IDs are in the $main_branch branch."
+           echo "All commit IDs are in the $main_branch branch."
+          else
+           echo "Not all commit IDs are in the $main_branch branch."
+           exit 1  # Mark the job as failed
           fi
 
-          exit $exit_code
+      - name: Print Commit IDs
+        if: always()
+        run: | 
+          echo "Final Commit IDs: ${{ steps.get_commits.outputs.commit_ids }}"
